### ISSUE TITLE
compilation of v5.3.1

### ISSUE THREAD

**Issue by Romeo01234** [vergecurrency/VERGE#984]
Hello all involved in solving this issue. Does not compile with new openssl version 1.1.1d.

Below is compilation error.  Indicate which Openssl version you are using to compile Verge-v5.3.1.

Thanks.

-----------------------------------------
-----error compilation below------
-----------------------------------------

  CC       src/lib/tls/src_lib_libtor_tls_a-tortls_openssl.o
In file included from src/lib/tls/tortls_openssl.c:61:0:
./src/lib/tls/tortls_internal.h:48:8: error: conflicting types for ‘SSL_SESSION_get_master_key’
 size_t SSL_SESSION_get_master_key(struct ssl_session_st *s,
        ^
In file included from src/lib/tls/tortls_openssl.c:48:0:
/usr/local/include/openssl/ssl.h:2007:15: note: previous declaration of ‘SSL_SESSION_get_master_key’ was here
 __owur size_t SSL_SESSION_get_master_key(const SSL_SESSION *sess,
               ^
src/lib/tls/tortls_openssl.c: In function ‘tor_tls_client_is_using_v2_ciphers’:
src/lib/tls/tortls_openssl.c:929:20: error: dereferencing pointer to incomplete type ‘SSL_SESSION {aka struct ssl_session_st}’
   ciphers = session->ciphers;
                    ^
src/lib/tls/tortls_openssl.c: At top level:
src/lib/tls/tortls_openssl.c:1577:1: error: conflicting types for ‘SSL_get_client_random’
 SSL_get_client_random(SSL *s, uint8_t *out, size_t len)
 ^
In file included from src/lib/tls/tortls_openssl.c:48:0:
/usr/local/include/openssl/ssl.h:2003:15: note: previous declaration of ‘SSL_get_client_random’ was here
 __owur size_t SSL_get_client_random(const SSL *ssl, unsigned char *out,
               ^
In file included from ./src/lib/crypt_ops/crypto_rand.h:16:0,
                 from src/lib/tls/tortls_openssl.c:31:
src/lib/tls/tortls_openssl.c: In function ‘SSL_get_client_random’:
src/lib/tls/tortls_openssl.c:1582:15: error: dereferencing pointer to incomplete type ‘SSL {aka struct ssl_st}’
   tor_assert(s->s3);
               ^
./src/lib/cc/compat_compiler.h:141:49: note: in definition of macro ‘PREDICT_LIKELY’
 #define PREDICT_LIKELY(exp) __builtin_expect(!!(exp), 1)
                                                 ^
./src/lib/log/util_bug.h:99:7: note: in expansion of macro ‘ASSERT_PREDICT_LIKELY_’
   if (ASSERT_PREDICT_LIKELY_(expr)) {                                   \
       ^
src/lib/tls/tortls_openssl.c:1582:3: note: in expansion of macro ‘tor_assert’
   tor_assert(s->s3);
   ^
src/lib/tls/tortls_openssl.c: At top level:
src/lib/tls/tortls_openssl.c:1590:1: error: conflicting types for ‘SSL_get_server_random’
 SSL_get_server_random(SSL *s, uint8_t *out, size_t len)
 ^
In file included from src/lib/tls/tortls_openssl.c:48:0:
/usr/local/include/openssl/ssl.h:2005:15: note: previous declaration of ‘SSL_get_server_random’ was here
 __owur size_t SSL_get_server_random(const SSL *ssl, unsigned char *out,
               ^
src/lib/tls/tortls_openssl.c:1603:1: error: conflicting types for ‘SSL_SESSION_get_master_key’
 SSL_SESSION_get_master_key(SSL_SESSION *s, uint8_t *out, size_t len)
 ^
In file included from src/lib/tls/tortls_openssl.c:48:0:
/usr/local/include/openssl/ssl.h:2007:15: note: previous declaration of ‘SSL_SESSION_get_master_key’ was here
 __owur size_t SSL_SESSION_get_master_key(const SSL_SESSION *sess,
               ^
Makefile:13764: recipe for target 'src/lib/tls/src_lib_libtor_tls_a-tortls_openssl.o' failed
make[2]: *** [src/lib/tls/src_lib_libtor_tls_a-tortls_openssl.o] Error 1
make[2]: Leaving directory '/home/lazarus/coinz/verge-5.3.1/src/tor'
Makefile:5001: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/lazarus/coinz/verge-5.3.1/src/tor'
Makefile:784: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by justinvforvendetta** [comment]
this is sort of a duplicate to https://github.com/vergecurrency/VERGE/issues/918

ill look at it today

**Comment by marpme** [comment]
We are actually just supporting OpenSSL versions <= 1.1.0l

**Comment by Romeo01234** [comment]
Thanks Marpme, but that version has stopped receiving support as of the 11th of September 2019.

https://www.openssl.org/source/

............."The 1.1.0 series is currently only receiving security fixes and will go out of support on 11th September 2019. All users of 1.0.2 and 1.1.0 are encouraged to upgrade to 1.1.1 as soon as possible.".................


For you info.

**Comment by marpme** [comment]
Currently upgrading to openssl-1.1.1 on my Mac and upgrading `tor` to `v0.4.1.X` let's see if they fixed the bug there, cause I knew that there were problems within this release (0.3.5.8) regarding certain SSL versions

**Comment by justinvforvendetta** [comment]
yeah I remember that as well. I'll install 1.1.1 as well n see if we can work thru it

**Comment by Romeo01234** [comment]
Sounds great. Hopefully a resolution is found soon.

**Comment by justinvforvendetta** [comment]
compiles perfect with 1.1.1

**Comment by Romeo01234** [comment]
Marpe, Justin. I'm using Ubuntu 16.04. Tried to compile but get the same error message as posted.

what commands are you using from the initial clone of the repository, down to compile command sequence.

Thanks.
