### PR TITLE
mac compiles using updated Travis and qt v5.6.1

### PR DESCRIPTION
**Pull request by mkinney**
I tried to compile on qt v5.8, but it kept complaining about qt needing -std=c++11. I did fix some 'invalid suffix on literal; C++11 requires a space between literal and identifier' issues and some warnings.

I think it's good, but I didn't fire up the mac binary nor test it.

Let me know if you have any questions/issues.

### CODE REVIEW

**Comment by vergecurrency** [comment]
@mkinney sweet! ill take a look today. looks like you didn't pull the latest source first though before making the pr (removed irc seeding and added checkpoints)

**Comment by justinvforvendetta** [comment]
@mkinney travis makes it much further into the mac build now.

In file included from qt/bitcoin.cpp:4:
./qt/bitcoingui.h:4:10: fatal error: 'QMainWindow' file not found
#include <QMainWindow>

im guessing this is a qt issue, looks related to this:
https://bugreports.qt.io/browse/QTBUG-36333

suggests changing 
#include <QMainWindow> 
to 
#include <QtWidgets/QMainWindow>

ill give it a whirl today if you're busy.
