### ISSUE TITLE
Can't compile on ubuntu 16.0.4

### ISSUE THREAD

**Issue by jimisan** [vergecurrency/VERGE#127]
rpcwallet.cpp: In function ‘json_spirit::Value sendmany(const Array&, bool)’:
rpcwallet.cpp:769:101: error: no matching function for call to ‘CWallet::CreateTransaction(std::vector<std::pair<CScript, long long int> >&, CWalletTx&, CReserveKey&, int64&, int&)’
     bool fCreated = pwalletMain->CreateTransaction(vecSend, wtx, keyChange, nFeeRequired, nChangePos);
                                                                                                     ^
In file included from rpcwallet.cpp:6:0:
wallet.h:188:10: note: candidate: bool CWallet::CreateTransaction(const std::vector<std::pair<CScript, long int> >&, CWalletTx&, CReserveKey&, int64_t&, int32_t&, const CCoinControl*)
     bool CreateTransaction(const std::vector<std::pair<CScript, int64_t> >& vecSend, CWalletTx& wtxNew, CReserveKey& reservekey, int64_t& nFeeRet, int32_t& nChange
          ^
wallet.h:188:10: note:   no known conversion for argument 1 from ‘std::vector<std::pair<CScript, long long int> >’ to ‘const std::vector<std::pair<CScript, long int> >&’
wallet.h:189:10: note: candidate: bool CWallet::CreateTransaction(CScript, int64_t, std::__cxx11::string&, CWalletTx&, CReserveKey&, int64_t&, const CCoinControl*)
     bool CreateTransaction(CScript scriptPubKey, int64_t nValue, std::string& sNarr, CWalletTx& wtxNew, CReserveKey& reservekey, int64_t& nFeeRet, const CCoinContr
          ^
wallet.h:189:10: note:   candidate expects 7 arguments, 5 provided
Makefile:2712: recipe for target 'libbitcoin_wallet_a-rpcwallet.o' failed
make[1]: *** [libbitcoin_wallet_a-rpcwallet.o] Error 1
make[1]: Leaving directory '/root/VERGE/src'
Makefile:524: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by justinvforvendetta** [comment]
use the 3.0 branch. master branch is in develop ment right now.
