### ISSUE TITLE
Qt 5.4 not available anymore

### ISSUE THREAD

**Issue by rickbakker** [vergecurrency/VERGE#150]
I tried to compile on MacOS El Capitan, followed the guide here in github. The link to Qt doesnt exist anymore. Tried downloading the latest release, and tried installing to the directory stated here but everytime i try this the installation just stops and hangs copying files. Then tried the same with version 5.6 but same issues. It starts copying files but then all of the sudden it hangs and won’t continue. 

Also tried to install the .dmg variant but that didnt work. Keeps crashing the moment i start the wallet. 

Should i update to the latest MacOS? Or should it be able to run on El Capitan?

**Comment by fabiotnt** [comment]
You can download the 5.4.2 version from archive folder

https://download.qt.io/archive/qt/5.4/5.4.2/

**Comment by rickbakker** [comment]
Gonna give that a try and and will report back! Thanks.

**Comment by Ssspore** [comment]
It still isn't working for Mac OS, does anyone else have another solution? I think this needs to be remedied soon.

**Comment by RualdOrdelman** [comment]
Same problem here. Installed the old Qt version, but at the 'make -j4' proces I got this error message:
 I followed the steps "To compile on Mac (OSX El Capitan, but test compiled on Mountain Lion v10.8): " from the manual.

bitcoinrpc.cpp:682:49: error: too many template arguments for class template
      'basic_socket_acceptor'
  ...basic_socket_acceptor<Protocol, SocketAcceptorService> > acceptor,
     ^                               ~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/boost/asio/basic_socket_acceptor.hpp:73:7: note: template is
      declared here
class basic_socket_acceptor
      ^
bitcoinrpc.cpp:692:42: error: too many template arguments for class template
      'basic_socket_acceptor'
  ...basic_socket_acceptor<Protocol, SocketAcceptorService> > acceptor,
     ^                               ~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/boost/asio/basic_socket_acceptor.hpp:73:7: note: template is
      declared here
class basic_socket_acceptor
      ^
bitcoinrpc.cpp:714:49: error: too many template arguments for class template
      'basic_socket_acceptor'
  ...basic_socket_acceptor<Protocol, SocketAcceptorService> > acceptor,
     ^                               ~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/boost/asio/basic_socket_acceptor.hpp:73:7: note: template is
      declared here
class basic_socket_acceptor
      ^
bitcoinrpc.cpp:789:18: error: no matching constructor for initialization of
      'ssl::context'
    ssl::context context(io_service, ssl::context::sslv23);
                 ^       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/boost/asio/ssl/impl/context.ipp:63:10: note: candidate
      constructor not viable: requires single argument 'm', but 2 arguments were
      provided
context::context(context::method m)
         ^
/usr/local/include/boost/asio/ssl/context.hpp:36:7: note: candidate constructor
      (the implicit copy constructor) not viable: requires 1 argument, but 2
      were provided
class context
      ^
bitcoinrpc.cpp:1099:18: error: no matching constructor for initialization of
      'ssl::context'
    ssl::context context(io_service, ssl::context::sslv23);
                 ^       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/boost/asio/ssl/impl/context.ipp:63:10: note: candidate
      constructor not viable: requires single argument 'm', but 2 arguments were
      provided
context::context(context::method m)
         ^
/usr/local/include/boost/asio/ssl/context.hpp:36:7: note: candidate constructor
      (the implicit copy constructor) not viable: requires 1 argument, but 2
      were provided

**Comment by jhanink** [comment]
see the PR attached to issue #166

**Comment by RualdOrdelman** [comment]
@jhanink hmmm install Qt 5.5.0 failed. Tried it several times but the installation proces hangs at a random point.

Any reason why not upgrading to another older version of Qt instead of going to the latest version (5.10.0)

**Comment by michpiatek** [comment]
I would say the only argument for older version would be 5.**9** being Long Term Support rel.

**Comment by jhanink** [comment]
updated to 5.10
https://github.com/vergecurrency/VERGE/pull/174

**Comment by RualdOrdelman** [comment]
@jhanink Nice, thanks. All Qt versions that I try to install will hang at at a random stage when copying the files. Very strange. Disabled the virus scanner etc but noting works.

**Comment by CamonZ** [comment]
@jhanink thanks dude 👍

**Comment by ekryski** [comment]
I'm going to submit a PR with updated build instructions. Since the build is passing in CI you won't need to mess with as much.

**Comment by jhanink** [comment]
@ekryski thanks. I canceled the qt 5.10 PR.

**Comment by topcatx** [comment]
@rickbakker the qt5.5 hangs when you try to install in `/usr/local/qt5` because it needs `root` and the session probably timing out. You can disable root session timeout or try the following (which I think is way safer)
```
sudo mkdir -p /usr/local/qt5 
sudo chown username /user/local/qt5
```

After this, when you install to the specific directory, the qt5.5 installation should work.

**Comment by justinvforvendetta** [comment]
yep we should be able to use the freshest qt now. im using 5.9.1 on ubuntu 17 and its working just fine. we aren't using webkit or webkitwidgets anymore, so we should have some wiggle room now.

**Comment by RualdOrdelman** [comment]
I've tested with Qt 5.10by changing build.sh and requirements.sh, so it deinstalled Qt5.5 and installed 5.10 (latest version). 

At building stage I got some errors. First these things before building, that doc-qt5 can't be found. 

checking for QT... yes
checking for QT_TEST... yes
checking for QT_DBUS... yes
checking for moc-qt5... no
checking for moc5... no
checking for moc... /usr/local/opt/qt@5.10/bin/moc
checking for uic-qt5... no

At building proces there errors:
/usr/local/opt/qt@5.10/lib/QtCore.framework/Headers/qcompilerdetection.h:567:6: error: Qt requires a C++11 compiler and yours does not seem to be that.
#    error Qt requires a C++11 compiler and yours does not seem to be that.

/usr/local/opt/qt@5.10/lib/QtCore.framework/Headers/qbasicatomic.h:61:4: error: "Qt requires C++11 support"
#  error "Qt requires C++11 support"
   ^
/usr/local/opt/qt@5.10/lib/QtCore.framework/Headers/qbasicatomic.h:93:13: error: unknown type name 'QAtomicOps'
    typedef QAtomicOps<T> Ops;
            ^
/usr/local/opt/qt@5.10/lib/QtCore.framework/Headers/qbasicatomic.h:93:23: error: expected member name or ';' after declaration specifiers
    typedef QAtomicOps<T> Ops;
    ~~~~~~~~~~~~~~~~~~^
/usr/local/opt/qt@5.10/lib/QtCore.framework/Headers/qbasicatomic.h:96:23: error: use of undeclared identifier 'QAtomicOpsSupport'
    Q_STATIC_ASSERT_X(QAtomicOpsSupport<sizeof(T)>::IsSupported, "template parameter is an integral of a size not supported on this platform");
                      ^
/usr/local/opt/qt@5.10/lib/QtCore.framework/Headers/qbasicatomic.h:96:53: error: no member named 'IsSupported' in the global namespace
    Q_STATIC_ASSERT_X(QAtomicOpsSupport<sizeof(T)>::IsSupported, "template parameter is an integral of a size not supported on this platform");

/usr/local/opt/qt@5.10/lib/QtCore.framework/Headers/qbasicatomic.h:96:5: error: type name requires a specifier or qualifier
    Q_STATIC_ASSERT_X(QAtomicOpsSupport<sizeof(T)>::IsSupported, "template parameter is an integral of a size not supported on this platform");

/usr/local/opt/qt@5.10/lib/QtCore.framework/Headers/qbasicatomic.h:98:14: error: use of undeclared identifier 'Ops'
    typename Ops::Type _q_value;
             ^
/usr/local/opt/qt@5.10/lib/QtCore.framework/Headers/qbasicatomic.h:98:19: error: expected a qualified name after 'typename'
    typename Ops::Type _q_value;
                  ^
/usr/local/opt/qt@5.10/lib/QtCore.framework/Headers/qbasicatomic.h:98:23: error: expected ';' at end of declaration list
    typename Ops::Type _q_value;
                      ^
                      ;
/usr/local/opt/qt@5.10/lib/QtCore.framework/Headers/qbasicatomic.h:102:44: error: use of undeclared identifier 'Ops'
    T load() const Q_DECL_NOTHROW { return Ops::load(_q_value); }
                                           ^
/usr/local/opt/qt@5.10/lib/QtCore.framework/Headers/qbasicatomic.h:102:54: error: use of undeclared identifier '_q_value'
    T load() const Q_DECL_NOTHROW { return Ops::load(_q_value); }
                                                     ^
/usr/local/opt/qt@5.10/lib/QtCore.framework/Headers/qbasicatomic.h:103:45: error: use of undeclared identifier 'Ops'
    void store(T newValue) Q_DECL_NOTHROW { Ops::store(_q_value, newValue); }
                                            ^
/usr/local/opt/qt@5.10/lib/QtCore.framework/Headers/qbasicatomic.h:103:56: error: use of undeclared identifier '_q_value'
    void store(T newValue) Q_DECL_NOTHROW { Ops::store(_q_value, newValue); }
                                                       ^
/usr/local/opt/qt@5.10/lib/QtCore.framework/Headers/qbasicatomic.h:105:51: error: use of undeclared identifier 'Ops'
    T loadAcquire() const Q_DECL_NOTHROW { return Ops::loadAcquire(_q_value); }
                                                  ^
/usr/local/opt/qt@5.10/lib/QtCore.framework/Headers/qbasicatomic.h:105:68: error: use of undeclared identifier '_q_value'
    T loadAcquire() const Q_DECL_NOTHROW { return Ops::loadAcquire(_q_value); }
                                                                   ^
/usr/local/opt/qt@5.10/lib/QtCore.framework/Headers/qbasicatomic.h:106:52: error: use of undeclared identifier 'Ops'
    void storeRelease(T newValue) Q_DECL_NOTHROW { Ops::storeRelease(_q_value, newValue); }
                                                   ^
/usr/local/opt/qt@5.10/lib/QtCore.framework/Headers/qbasicatomic.h:106:70: error: use of undeclared identifier '_q_value'
    void storeRelease(T newValue) Q_DECL_NOTHROW { Ops::storeRelease(_q_value, newValue); }
                                                                     ^
/usr/local/opt/qt@5.10/lib/QtCore.framework/Headers/qbasicatomic.h:110:86: error: use of undeclared identifier 'Ops'
    static Q_DECL_CONSTEXPR bool isReferenceCountingNative() Q_DECL_NOTHROW { return Ops::isReferenceCountingNative(); }
                                                                                     ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]

**Comment by RualdOrdelman** [comment]
Qt 5.7 is the latests version that is working well. I've created a build with Qt 5.7.

**Comment by justinvforvendetta** [comment]
5.9 works in ubuntu 17. im using the normal instructions, not the script

**Comment by rickbakker** [comment]
@topcatx thanks man, gonna try that. That could very well be the issue indeed.

**Comment by rickbakker** [comment]
Ok so i finally got it to work. Just compiled the new release and that works fine!
